version: "3"

services:
  dropper-backend:
    container_name: dropper-backend
    build: ./
    image: dropper-backend/latest
    restart: unless-stopped
    ports:
      - 5151:8080
    environment:
      - NODE_ENV=production
      - PORT=8080
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_KEY=$SUPABASE_KEY
