version: "3"

services:
  dropper-backend:
    container_name: dropper-backend
    build: ./
    image: dropper-backend/latest
    restart: unless-stopped
    ports:
      - 5151:8080
    environment:
      - NODE_ENV=production
      - PORT=8080
      - SUPABASE_URL=$SUPABASE_URL
      - SUPABASE_KEY=$SUPABASE_KEY
    network_mode: $NETWORK_MODE
    labels:
      traefik.enable: $TRAEFIK_ENABLE
      traefik.http.routers.dropper.entrypoints: $TRAEFIK_ENTRYPOINTS
      traefik.http.routers.dropper.rule: $TRAEFIK_RULE
      traefik.http.routers.dropper.tls: $TRAEFIK_TLS
      traefik.http.routers.dropper.tls.certresolver: $TRAEFIK_CERTRESOLVER
